version: "3.8"

networks:

services:
  frontend_dev:
    build:
      context: .
      dockerfile: DockerFile
    container_name: fe_dev
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env:rw
