version: "3.8"

networks:
  fe-i:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
    volumes:
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - frontend
    networks:
      - fe-i
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_fe
    volumes:
      - ./.env:/app/.env:rw
    networks:
      - fe-i
